#!/usr/bin/env bash

: << DOCXX
------------------------------------------------------------------------------
# tmrestore
# =========
#   Description: Restore project settings from Time Machine backup. 
#         Usage: tmrestore [options] backup_volume
#    Parameters: [-f] Force the staging directory to be overwritten
#   
	This script will allow you to choose a backupset from the backup_volume.
	
	We rely on mackup as a source of configuration locations. By all means, 
	use mackup in conjunction with this script.

DOCXX
#------------------------------------------------------------------------------

ETC_PATH=HB_ETC

function get_config {
	# Get content of cfg file into variables
	# $1 = full path to cfg file
    export APP=$(crudini --get $1  application name)
    # Files relative to $HOME
    export FILES=$(crudini --get $1 configuration_files 2>/dev/null)
    # Files relative to (normally)  $HOME/.config
    export XDG_FILES=$(crudini --get $1 xdb_configuration_files 2>/dev/null)
}
